# Generated by Django 3.2 on 2024-03-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='documento_tipo',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='telefone',
        ),
    ]
