# Generated by Django 3.2 on 2024-04-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_auto_20210624_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoramento',
            name='logo',
            field=models.CharField(default='default_logo.png', max_length=50, verbose_name='logo'),
        ),
    ]
