# Generated by Django 3.2 on 2024-11-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_monitoramento_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prometheus',
            options={'verbose_name': 'Prometheus', 'verbose_name_plural': 'Prometheus'},
        ),
    ]
