# Generated by Django 3.2 on 2024-12-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0011_alter_ambientevirtual_options'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenants', models.CharField(max_length=255, verbose_name='Grupo de Rede')),
            ],
            options={
                'verbose_name': 'Grupo de Rede',
                'verbose_name_plural': 'Grupos de Redes',
            },
        ),
        migrations.CreateModel(
            name='ServidorTenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.servidor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenants')),
            ],
            options={
                'verbose_name': 'Grupo de Rede',
                'verbose_name_plural': 'Grupos de Redes',
                'unique_together': {('servidor', 'tenant')},
            },
        ),
    ]
