# Generated by Django 3.2 on 2024-11-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0007_equipamento_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientevirtual',
            name='status',
            field=models.CharField(choices=[('ON', 'Ativo'), ('OFF', 'Inativo')], default='AT', max_length=3, verbose_name='status'),
        ),
    ]
