# Generated by Django 3.2 on 2024-11-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0007_equipamento_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='servicos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='serviços'),
        ),
    ]
