# Generated by Django 3.2 on 2024-11-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0008_servidor_servicos'),
        ('infra', '0009_alter_ambientevirtual_status'),
    ]

    operations = [
    ]
