# Generated by Django 3.2 on 2024-11-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0010_merge_20241126_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambientevirtual',
            options={'verbose_name': 'Ambiente Virtual', 'verbose_name_plural': 'Ambientes Virtuais'},
        ),
    ]
